version: '3.6'

services:
  mongodb:
    image: mongo:4
    env_file: .env
    ports:
      - "27017-27019:27017-27019"
  mongodb_web:
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8091:8081"
